### PR TITLE
Issue 14 required dependencies added

### PR DESCRIPTION
**Pull request by Mac16661**
reach out to me if any additional configuration changes are required.

### CODE REVIEW

**Comment by Mac16661** [comment]
can somebody explain why I am getting conflicts and how to resolve it.

**Comment by mcopik** [comment]
@Mac16661 You modified unnecessarily `README.md` in several places - please check the diff in "Files Changed".

**Comment by mcopik** [comment]
@Mac16661 If you cancel your changes to the `README.md`, I will be able to merge it.

**Comment by Mac16661** [comment]
ok , let me make another request

**Comment by mcopik** [comment]
@Mac16661 Please don't open a new PR - just push changes to your branch and the PR will be automatically updated with new content on this branch.

**Comment by Mac16661** [comment]
sorry, I did open a new PR

**Pull request closed without merging**
