### PR TITLE
Update dependencies.cmake

### PR DESCRIPTION
**Pull request by Origin-yy**
Only find specific versions of the spdlog and cereal libraries.

### CODE REVIEW

**Comment by mcopik** [comment]
@Origin-yy Thanks so much! This should solve the problem, at least for now :)

Could we also update `cereal` targets to use the namespace? This would solve the issue you experienced when using packaged `cereal`.

**Comment by Origin-yy** [comment]
I don't think it's necessary. Cereal::cereal is not needed in the 1.3 version of the cereal library. It is only needed in the higher version, and the 1.3 version still uses cereal.
The modified find_package will only specifically search for version 1.3 cereal and version 1.8 spdlog. If these two specific versions are not installed locally, the libraries of these two specific versions will be installed in the project's _deps directory without affecting Other versions of the library have been installed locally (just like the previous code), I have tested it.
The original code is very good, just ignore the problem that the updated spdlog library and cerea library may not match the current project.

**Comment by Origin-yy** [comment]
Can this be modified?

**Comment by Origin-yy** [comment]
For the problem of dependent library versions, we have two options:
One is to choose a specific version of the library, even though new versions will come out later. This will ensure that no compatibility issues arise. The other is that we get the latest version of the library when we run the code, but the new version may cause compatibility issues with the original code and need not be modified, as it is now, I may not express clearly, but you should be able to understand, you think it should how to choose?

**Comment by mcopik** [comment]
@Origin-yy Thanks for the contribution! For now, let's use old versions - we will upgrade at some point in the future.

**Pull request merged**
