### PR TITLE
Libfabric sarus fix compiler errors

### PR DESCRIPTION
**Pull request by mattnappo**
The `libfabric-sarus` branch doesn't compile in its current state. This is due to:
* GNI code not being properly excluded/included based on build parameters. Fixed by adding `#ifdef USE_GNI_AUTH` flags when appropriate
* An issue with the JSON parser logic for the executor manager config which requires a sarus-like config even when the sandbox type is `process` 

I'm creating this PR so that future work off this branch has a working baseline.

### CODE REVIEW

**Comment by mcopik** [comment]
@mattnappo Can you please remove the `.gitignore` file from the merge? I will be able to merge PR then :-)

**Comment by mattnappo** [comment]
Sure. But if I may ask, why don't we commit the gitignore?

**Comment by mcopik** [comment]
@mattnappo Of course we want it :-) But you added this in two different commits, in different PRs, and this will  lead to conflicts in future.

**Comment by mcopik** [comment]
LGTM, thanks!

**Pull request merged**
